# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tests/profile.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13tests/profile.proto"=\n\rProfileCreate\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65'
    b'mail\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05"Z\n\nProfileGet\x12\n\n\x02id\x18\x01 '
    b'\x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61'
    b'ge\x18\x04 \x01(\x05\x12\x12\n\ncreated_at\x18\x05 \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "tests.profile_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _PROFILECREATE._serialized_start = 23
    _PROFILECREATE._serialized_end = 84
    _PROFILEGET._serialized_start = 86
    _PROFILEGET._serialized_end = 176
# @@protoc_insertion_point(module_scope)
